version: 2.1

jobs:
  build:
    # machine:
    #   image: ubuntu-2204:2022.04.2
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
      - image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test!xx123
      - image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
          MSSQL_SA_PASSWORD: test!xx123
          ACCEPT_EULA: Y
    docker_layer_caching: true
          
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - run: echo hi
      - run: dotnet test src/cicd-sandbox.sln