version: 2.1
  
jobs:
  prep-alpha:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Add local package store
          command: |
            mkdir packages
            dotnet nuget add source ~/project/packages --name Local
      - run: dotnet nuget list source
      - run: ls -l
      - run: dotnet build src/mathtone-magic.sln
      #- pack-pre:
      #    project: src/CodeMagic/CodeMagic.csproj
      #    suffix: alpha
      - persist_to_workspace:
          root: .
          paths:
            - .
  
workflows:
  
  build:
    jobs:
      - prep-alpha:
          context: MATHTONE_DEV
          #filters:
          #  branches:
          #    only:
          #      - /prerelease\/.*/
     