version: 2.1
commands:
  swapref:
    parameters:
      proj:
         type: string
      ref:
         type: string
      pkg:
         type: string
    steps:
      - run: dotnet remove << parameters.proj >> reference << parameters.ref >>
      - run: dotnet add << parameters.proj >> package << parameters.pkg >> --source ~/project/packages --prerelease
jobs:
  prep-project:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run: dotnet build src/mathtone-magic.sln
  run-tests:
    parameters:
      suffix:
        type: string
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
      - image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test1234
      - image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
          MSSQL_SA_PASSWORD: test!1234
          ACCEPT_EULA: Y
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: dotnet test src/mathtone-magic.sln --configuration Release
      - persist_to_workspace:
          root: .
          paths:
            - .
  pack-projects:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    parameters:
      suffix:
        type: string
      prerelease:
        type: boolean
    steps:
      - checkout
      - run: dotnet restore src/mathtone-magic.sln
      - when:
          condition:
            not:
              equal: [ << parameters.suffix >> , '' ]
          steps:
            - run: dotnet pack src/mathtone-magic.sln --configuration Release --output packages --version-suffix << parameters.suffix >>
      # swap refs
workflows:
  build:
    jobs:
      - prep-project
      - run-tests:
          suffix: alpha
          requires:
            - prep-project
      - pack-projects:
          name: Pack Alpha
          suffix: alpha
          prerelease: true
          requires:
            - run-tests
      - pack-projects:
          name: Pack Beta
          suffix: beta
          prerelease: true
          requires:
            - run-tests
      - pack-projects:
          name: Pack Release
          suffix: ''
          prerelease: false
          requires:
            - run-tests
      # - pack-projects:
      #     suffix: alpha
      #     requires:
      #       - prep-project
      # - pack-beta
      # - prep-project:
      #     context: MATHTONE_DEV
      # - split-packages:
      #     context: MATHTONE_DEV
      #     suffix: alpha
      #     requires:
      #      - prep-project
      # - run-unit-tests:
      #    context: MATHTONE_DEV
      #    requires:
      #      - split-packages
      # - publish-artifactory:
      #     context: MATHTONE_DEV
      #     suffix: -alpha
      #     requires:
      #       - run-unit-tests

        
      # - deploy-beta-artifactory:
      #     type: approval
      #     requires:
      #       - build
      #       - request-approval
      
          #filters:
          #  branches:
          #    only:
          #      - /prerelease\/.*/
     