version: 2.1
commands:
  swapref:
    parameters:
      proj:
         type: string
      ref:
         type: string
      pkg:
         type: string
    steps:
      - run: dotnet remove << parameters.proj >> reference << parameters.ref >>
      - run: dotnet add << parameters.proj >> package << parameters.pkg >> --source ~/project/packages --prerelease
  
jobs:
 prep-project:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      # - run:
      #     name: Add local package store
      #     command: |
      #       mkdir packages
      #       dotnet nuget add source ~/project/packages --name Local
      # - run: dotnet nuget list source
      # - run: ls -l
      - run: dotnet build src/mathtone-magic.sln
      - run: dotnet test src/mathtone-magic.sln
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - .
workflows:
  
  build:
    jobs:
      - prep-project
      # - pack-beta
      # - prep-project:
      #     context: MATHTONE_DEV
      # - split-packages:
      #     context: MATHTONE_DEV
      #     suffix: alpha
      #     requires:
      #      - prep-project
      # - run-unit-tests:
      #    context: MATHTONE_DEV
      #    requires:
      #      - split-packages
      # - publish-artifactory:
      #     context: MATHTONE_DEV
      #     suffix: -alpha
      #     requires:
      #       - run-unit-tests

        
      # - deploy-beta-artifactory:
      #     type: approval
      #     requires:
      #       - build
      #       - request-approval
      
          #filters:
          #  branches:
          #    only:
          #      - /prerelease\/.*/
     