version: 2.1
commands:
  swapref:
    parameters:
      proj:
         type:
            string
      ref:
         type:
            string
      pkg:
         type:
            string
    steps:
      - run: dotnet remove << parameters.proj >> reference << parameters.ref >>
      - run: dotnet add << parameters.proj >> package << parameters.pkg >> --source ~/project/packages --prerelease
  pack-pre:
    parameters:
      project:
        type:
          string
      suffix:
        type:
          string
    steps:
      - run:
          name: Build and Pack << parameters.project >>
          command: |
            dotnet build << parameters.project >> --configuration Release
            dotnet pack << parameters.project >> --configuration Release --no-build --output packages --version-suffix << parameters.suffix >> 
jobs: 
  prep-project:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Add local package store
          command: |
            mkdir packages
            dotnet nuget add source ~/project/packages --name Local
      - run: dotnet nuget list source
      - run: ls -l
      - run: dotnet build src/mathtone-magic.sln
      - persist_to_workspace:
          root: .
          paths:
            - .
  split-packages:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - attach_workspace:
          at: .
      - run: dotnet nuget add source ~/project/packages --name Local
      - pack-pre:
          project: src/SDK/Mathtone.Sdk.Data/Mathtone.Sdk.Data.csproj
          suffix: alpha
      - swapref:
          proj: src/SDK/Mathtone.Sdk.Data.Sql/Mathtone.Sdk.Data.Sql.csproj
          ref: ../Mathtone.Sdk.Data/Mathtone.Sdk.Data.csproj
          pkg: Mathtone.Sdk.Data.0.0.0-alpha
      
  run-unit-tests:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
      - image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test1234
      - image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
          MSSQL_SA_PASSWORD: test!1234
          ACCEPT_EULA: Y
    steps:
      - attach_workspace:
          at: .
      - run:
         name: run unit tests
         command:  dotnet test src/mathtone-magic.sln
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  
  build:
    jobs:
      - prep-project:
          context: MATHTONE_DEV
      - split-packages:
          context: MATHTONE_DEV
          requires:
           - prep-project
      - run-unit-tests:
         context: MATHTONE_DEV
         requires:
           - split-packages
          #filters:
          #  branches:
          #    only:
          #      - /prerelease\/.*/
     