version: 2.1
commands:
  get-version:
    steps:
      - run: |
          branch=$CIRCLE_BRANCH
          ver=${branch/"release/"/""}
          suffix=${ver#*-}
          build=${ver%-*}
          if  [[ $suffix == "" ]]; then
            echo NO SUFFIX
            echo "export PKG_SFX_TAG=""" >> $BASH_ENV
            
          else
            echo SUFFIX FOUND
            echo "export PKG_SFX_TAG=${--version-suffix $suffix}" >> $BASH_ENV
          fi
          
          echo "export PKG_VER=$build" >> $BASH_ENV
          echo "export PKG_SFX=$suffix" >> $BASH_ENV
          
jobs:
  get-code:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - run: |
         pwd
      - run: |
          mkdir temp
          mkdir packages
          ls -l
      - run: dotnet build tools/build-util/build-util.csproj --output temp
      - run: dotnet temp/build-util.dll src/mathtone-magic.sln
      - run: |
          branch=$CIRCLE_BRANCH
          ver=${branch/"release/"/""}
          suffix=${ver#*-}
          build=${ver%-*}

          echo build- ${build} version- ${suffix}
      - persist_to_workspace:
          root: .
          paths:
            - src
            - tools
            - packages
            - temp/process-sln.sh
  shatter-test-projects:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
      - image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test!1234
      - image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
          MSSQL_SA_PASSWORD: Test!1234
          ACCEPT_EULA: Y
    working_directory: /mnt/ramdisk
    steps:
      - attach_workspace:
          at: .
      - get-version
      - run: |
          echo "SUFFIX TAG: $PKG_SFX_TAG"
          dotnet restore src/mathtone-magic.sln
          dotnet nuget remove source nuget.org
          dotnet nuget add source /mnt/ramdisk/packages -n local
          bash temp/process-sln.sh
      - run: dotnet test src/mathtone-magic.sln --configuration Release
      - persist_to_workspace:
          root: .
          paths:
            - packages
  publish-artifactory:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Add Artifactory"
          command: dotnet nuget add source https://mathtone.jfrog.io/artifactory/api/nuget/v3/mathtone-dev --name Mathtone-Dev --username ${ARTIFACTORY_USER} --password ${ARTIFACTORY_PWD} --store-password-in-clear-text
      - run:
         name: Publish to Atifactory
         command: |
            dotnet nuget push packages/*.nupkg --source Mathtone-Dev

  publish-nuget:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - attach_workspace:
          at: .
      - run:
         name: Publish to Nuget
         command: dotnet nuget push packages/*.nupkg --api-key ${NUGET_PUBLISH_KEY} --source https://api.nuget.org/v3/index.json
workflows:
  build-release:
    jobs:
      - get-code
      - shatter-test-projects:
          context: MATHTONE_DEV
          requires:
            - get-code 
      - publish-artifactory:
          context: MATHTONE_DEV
          requires:
            - shatter-test-projects
      - approve-ship:
          context: MATHTONE_DEV
          type: approval
          requires:
            - publish-artifactory
      - publish-nuget:
          context: MATHTONE_DEV
          requires:
            - approve-ship